Back/registration tests
f1nal3/Juniorgram pull request #269
Opened 2021-07-05 12:17 UTC by fisyamaloy

There are 2 connections at the same time to 2 different DB in DataAccess.Tests. When we connect to second DB, connection with first DB are lost. Here we get some problems, which I solve by not the best way, adding new test-case, where first connection are closing, before we connect to another DB.

2021-07-08 20:13 UTC, HRenata requested changes

2021-07-08 20:13 UTC, HRenata commented on Client/Client.Qt/ConnectionManager.hpp
> +    inline static const std::string   address = "127.0.0.1";
return back address and port

2021-07-08 20:13 UTC, HRenata commented on DataAccess/DataAccess.Static/PostgreAdapter.hpp
> +        "dbname=postgres user=postgres hostaddr=127.0.0.1 port=5432 password=123";
return back dbname and password

2021-07-12 00:07 UTC, HRenata approved these changes

2021-07-13 19:27 UTC, StasDash approved these changes

2021-07-13 19:31 UTC, merged