Stress tester
f1nal3/Juniorgram pull request #310
Opened 2021-07-22 16:51 UTC by vDrWool

2021-08-05 17:28 UTC, Svidunovich commented
Do we need all the comments in this pr?

2021-08-05 17:29 UTC, vDrWool commented
> Do we need all the comments in this pr?
> If not, fix it
> plz

2021-08-05 17:33 UTC, vDrWool commented
Comments in Tester.cpp I won't to delete becase they are about how it works (I guess it a bad idea).

2021-08-08 14:23 UTC, Svidunovich requested changes

2021-08-08 14:23 UTC, Svidunovich commented on PerformanceTest/ArgumentParser.cpp
> +				//&& std::all_of(value.cbegin(), value.cend(), std::isdigit);
Do we need these comments?

2021-08-08 14:23 UTC, Svidunovich commented on PerformanceTest/SimpleTimer.cpp
> +        _end          = {};
Please check spaces in all documents

2021-08-08 17:54 UTC, Svidunovich approved these changes

2021-08-10 11:43 UTC, StasDash approved these changes

2021-08-10 12:07 UTC, GuskoMaksim approved these changes

2021-08-10 14:30 UTC, merged