Fix message storing
f1nal3/Juniorgram pull request #328
Opened 2021-07-29 16:13 UTC by fisyamaloy

2021-07-30 13:50 UTC, f1nal3 requested changes

2021-07-30 13:50 UTC, f1nal3 commented on CMakeLists.txt
> +    add_compile_options(/W3 /WX)
How does that correspond to this PR name? Why should it be changed?

2021-07-30 13:50 UTC, f1nal3 commented on DataAccess/DataAccess.Postgre/DataBaseOptions.hpp
> -        "dbname=juniorgram user=postgres hostaddr=127.0.0.1 port=5432";
Was there any change to our database naming? Why did it had to happen? Currently that DB is empty:
<img width="476" alt="image" src="https://user-images.githubusercontent.com/13378692/127662554-f42234d8-ed95-4243-87cf-d4dc0cfff235.png">

2021-07-30 13:50 UTC, f1nal3 commented on Network/Public/Include/Network/Primitives.hpp
> +    struct MessageStoringInfo : MessageInfo
Do we use the old message info anywhere? Is there a reason to keep the old one?

2021-07-30 13:50 UTC, f1nal3 commented on Server/Server.Exec/MainServer.cpp
>      try
What is the motivation to changing MainServer.cpp?

2021-07-30 13:50 UTC, f1nal3 commented
K, never mind the review, didn't notice it's a draft :D

2021-07-30 15:01 UTC, fisyamaloy commented
> K, never mind the review, didn't notice it's a draft :D

xD

2021-08-04 13:52 UTC, vDrWool approved these changes

2021-08-04 15:22 UTC, GuskoMaksim approved these changes

2021-08-04 15:26 UTC, merged