Fix ChannelListWindow
f1nal3/Juniorgram pull request #342
Opened 2021-08-07 11:54 UTC by GuskoMaksim

2021-08-08 06:40 UTC, vDrWool requested changes

2021-08-08 06:40 UTC, vDrWool commented on Client/Client.Qt/Widgets/ChannelListWindow.cpp
> +void ChannelListWindow::setChannels(std::vector<Network::ChannelInfo>&& channels_)
"channels_" is strange naming a bit for func arg. I guess it needs to change.

2021-08-09 13:21 UTC, vDrWool approved these changes

2021-08-09 13:55 UTC, StasDash approved these changes

2021-08-09 15:01 UTC, merged