Front leaving and deleting a channel
f1nal3/Juniorgram pull request #457
Opened 2021-11-03 15:04 UTC by GuskoMaksim

2021-11-04 13:51 UTC, vDrWool approved these changes

2021-11-04 16:06 UTC, Orange-hanter requested changes

2021-11-04 16:06 UTC, Orange-hanter commented on Client/Client.Qt/Widgets/ChatWidget.hpp
> +    ///
Empty documentation is not documentation!)

2021-11-04 16:06 UTC, Orange-hanter commented on DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
> +    if (creatorlID != channel.creatorID)
Right in the time!

2021-11-18 16:19 UTC, Orange-hanter requested changes

2021-11-23 17:04 UTC, f1nal3 commented
@Orange-hanter maybe there's a point in assigning this to someone else? or maybe finishing that ourselves?

I mean, it's a 20 days PR :)

2021-11-26 11:44 UTC, Orange-hanter approved these changes

2021-11-26 11:45 UTC, merged