Create Setup server on localhost.md
f1nal3/Juniorgram pull request #458
Opened 2021-11-03 15:34 UTC by Orange-hanter

2021-11-03 16:08 UTC, f1nal3 requested changes

2021-11-03 16:08 UTC, f1nal3 commented on Docs/Setup server on localhost.md
> +3. Create a table with an arbitrary name.
A table or a database?

2021-11-03 16:08 UTC, f1nal3 commented on Docs/Setup server on localhost.md
> +4. Done, the server is running locally.
The server is running locally after part 2 =)

2021-11-03 16:08 UTC, f1nal3 commented on Docs/Setup server on localhost.md
> +1. In ServerInfo.cpp, specify the address of the local host
I'd separate this from the rest cause this really concerns Client and has nothing to do with the server. Can be transferred to the last part with all the client parts there

2021-11-03 16:08 UTC, f1nal3 commented on Docs/Setup server on localhost.md
> +      constexpr std :: string_view address = "127.0.0.1"
inconsistent with line 17 std::uint16_t and here std :: string view.

2021-11-03 16:08 UTC, f1nal3 commented on Docs/Setup server on localhost.md
> +"dbname = your_bdname user = postgres hostaddr = 127.0.0.1 port = 5432 password = your_password"
this is also c++ code :)

2021-11-17 15:02 UTC, f1nal3 approved these changes

2021-11-17 15:17 UTC, StasDash approved these changes

2021-11-17 15:18 UTC, merged