Shortcut chat page
f1nal3/Juniorgram pull request #459
Opened 2021-11-10 17:03 UTC by Sirzhatina

2021-11-11 13:18 UTC, GuskoMaksim commented on Client/Client.Qt/Widgets/InputFields.cpp
> +}
Add a line break at the end, the rule described on WIKI

2021-11-11 13:27 UTC, GuskoMaksim requested changes

2021-11-11 13:27 UTC, GuskoMaksim commented on Client/Client.Qt/Widgets/TextEdit.cpp
> +    connect(_messageInput.get(), SIGNAL(messageSent()), this, SLOT(sendButtonClick()));
I think you should stick with the style of "connect" one line above

2021-11-11 13:41 UTC, StasDash requested changes

2021-11-11 13:41 UTC, StasDash commented on Client/Client.Qt/Widgets/InputFields.hpp
> +#include <QKeyEvent>
This line is unnecessary(all events are included in source file)

2021-11-11 13:41 UTC, StasDash commented on Client/Client.Qt/Widgets/InputFields.hpp
> +    void messageSent();
This a common-case widget, so better common-name required

2021-11-11 16:00 UTC, GuskoMaksim approved these changes

2021-11-12 08:19 UTC, GuskoMaksim approved these changes

2021-11-17 15:19 UTC, StasDash approved these changes
Signals are for later

2021-11-18 15:57 UTC, Orange-hanter requested changes

2021-11-18 15:57 UTC, Orange-hanter commented on Client/Client.Qt/Widgets/InputFields.cpp
> +        QTextEdit::keyPressEvent(keyEvent);
Call parent handler in any case.

2021-11-18 16:05 UTC, Sirzhatina commented on Client/Client.Qt/Widgets/InputFields.cpp
> +        QTextEdit::keyPressEvent(keyEvent);
You mean removing else part, don't you?

2021-11-19 15:07 UTC, Orange-hanter approved these changes

2021-11-19 15:13 UTC, merged