Login kick fix
f1nal3/Juniorgram pull request #461
Opened 2021-11-16 14:47 UTC by StasDash

2021-11-18 15:22 UTC, Orange-hanter requested changes

2021-11-18 15:22 UTC, Orange-hanter commented on Server/Server.Core/Server.Core.Static/Server.cpp
> +            /// FIXME: This function always return true
convert to doxygen style

2021-11-18 15:22 UTC, Orange-hanter commented on Server/Server.Core/Server.Core.Static/Server.hpp
>       * @brief Method for sending the message disconnecting to the server.
Correct grammar please

2021-11-18 15:59 UTC, Orange-hanter approved these changes

2021-11-19 15:16 UTC, dbski approved these changes

2021-11-19 15:31 UTC, merged