Server logging
f1nal3/Juniorgram pull request #467
Opened 2021-12-12 23:14 UTC by Sirzhatina

2021-12-16 14:18 UTC, Orange-hanter requested changes

2021-12-16 14:18 UTC, Orange-hanter commented on Server/Server.Core/Server.Core.Static/Server.cpp
> +    out << "Removing client [" << client->getID() << "]";
This is not the best way to create regular string...
https://quick-bench.com/q/IzYOZ2eR2Qu6Lu93iLRvuRTHqZ8

2021-12-16 15:31 UTC, Orange-hanter approved these changes

2021-12-17 12:05 UTC, Orange-hanter approved these changes

2021-12-17 13:21 UTC, f1nal3 approved these changes

2021-12-17 13:33 UTC, merged