Added message of incorrect registration
f1nal3/Juniorgram pull request #477
Opened 2022-01-12 15:11 UTC by Agrifon

2022-02-03 16:12 UTC, Orange-hanter commented
1. Please make the window more readable
2. Use the coordinates of the parent window. I have incorrect behaviour in dual monitor mode.

2022-02-07 06:34 UTC, Agrifon commented
For some reason, the test does not pass =(

2022-02-09 15:19 UTC, f1nal3 requested changes

2022-02-09 15:19 UTC, f1nal3 commented on CMakeSettings.json
> +      "generator": "Ninja",
Do we need this file?

2022-02-09 15:19 UTC, f1nal3 commented on Client/Client.Qt/Widgets/PopupWidget.hpp
> +void messageOut(std::shared_ptr<PopupWidget> popupWidget, QString text);
newline at the end of file

2022-02-09 15:19 UTC, f1nal3 commented on Client/Client.Qt/Widgets/PopupWidget.cpp
> +}
newline at the end of file

2022-02-09 15:19 UTC, f1nal3 commented on Client/Client.Qt/Widgets/PopupSystemMessage.hpp
> +#endif  // POPUP_SYSTEM_MESSAGE_H
newline at the end of file

2022-02-09 15:19 UTC, f1nal3 commented on Client/Client.Qt/Widgets/PopupSystemMessage.cpp
> +}
newline at the end of file

2022-02-09 15:19 UTC, f1nal3 commented on Client/Client.Qt/Pages/RegistrationPage.hpp
> +};
newline at the end of file

2022-02-09 15:19 UTC, f1nal3 commented on CMakeSettings.json
> +}
newline at the end of file

2022-02-10 13:10 UTC, Orange-hanter requested changes

2022-02-10 13:10 UTC, Orange-hanter commented on Client/Client.Qt/Widgets/PopupWidget.hpp
> +void messageOut(std::shared_ptr<PopupWidget> popupWidget, QString text);
Do you use this function anywhere? Looks like no. Why we should keep it?

2022-02-10 13:10 UTC, Orange-hanter commented on README.md
> +
Remove please

2022-02-10 13:10 UTC, Orange-hanter commented on Client/Client.Qt/Widgets/PopupWidget.cpp
> +        _messageText = std::make_unique<QLabel>(text, this);
In case of uninitialized __messageText_ you are setting the _text_ value two times.

2022-02-11 16:46 UTC, Orange-hanter approved these changes

2022-02-11 16:48 UTC, slavexx approved these changes

2022-02-15 16:17 UTC, f1nal3 commented on CMakeSettings.json
> +      "generator": "Ninja",
It is considered a good gesture to somehow comment on the resolved code review issues.

2022-02-17 12:22 UTC, Orange-hanter approved these changes

2022-02-17 15:53 UTC, f1nal3 approved these changes

2022-02-17 15:54 UTC, merged