Transfer Client.CLI and Client.Core to use a Logger
f1nal3/Juniorgram pull request #500
Opened 2022-03-02 19:36 UTC by KanstantsinTaukach

2022-03-03 17:45 UTC, Orange-hanter requested changes

2022-03-03 17:45 UTC, Orange-hanter commented on Client/Client.Core/Client.Core.Static/Client.hpp
> +#include <FileLogger.hpp>
It's better to move FileLogger header to cpp part. It should improve build time and avoid unnecessary dependencies.

2022-03-03 17:45 UTC, Orange-hanter commented on Client/Client.Core/Client.Core.Static/CMakeLists.txt
> -target_include_directories(${TARGET}
Please, do not update format of CMake unless you have a reason for this

2022-03-16 19:49 UTC, fisyamaloy commented on Client/Client.CLI/App.cpp
> +        Base::Logger::FileLogger::getInstance().log(out.str(), Base::Logger::LogLevel::INFO);
Is it necessary to log each message? Maybe it is better to log only row such as "Message history recieved"

2022-03-17 14:23 UTC, KliKonNik commented
Probably it's better to use **std::string()** instead of **out.str()**, isn't it?

2022-03-30 08:46 UTC, Orange-hanter requested changes

2022-03-30 08:46 UTC, Orange-hanter commented on Client/Client.Qt/ConnectionManager.cpp
> +        Base::Logger::FileLogger::getInstance().log("FAILED sending", Base::Logger::LogLevel::INFO);
Wrong Log lever. In this case should be ERROR

2022-03-30 08:46 UTC, Orange-hanter commented on Client/Client.Qt/ConnectionManager.cpp
> +        Base::Logger::FileLogger::getInstance().log("Reaction update FAILED", Base::Logger::LogLevel::INFO);
same

2022-03-30 08:46 UTC, Orange-hanter commented on Client/Client.Qt/ConnectionManager.cpp
> +        Base::Logger::FileLogger::getInstance().log("FAILED DELETING", Base::Logger::LogLevel::INFO);
same

2022-03-30 08:46 UTC, Orange-hanter commented on Client/Client.Qt/ConnectionManager.cpp
> +        Base::Logger::FileLogger::getInstance().log("UNKNOWN deleting message code", Base::Logger::LogLevel::INFO);
Loglevel::WARNING

2022-03-30 08:46 UTC, Orange-hanter commented on Client/Client.Qt/Pages/RegistrationPage.cpp
> +            Base::Logger::FileLogger::getInstance().log("some field is empty", Base::Logger::LogLevel::INFO);
Here should be WARNING

2022-03-30 08:46 UTC, Orange-hanter commented on Client/Client.Core/Client.Core.Static/Client.cpp
> +                    "[Client][Warning] unimplemented[" + std::to_string(uint32_t(message.mHeader.mMessageType)) + "]",
**[Client][Warning]** are superfluous. Also, the type of log level should be WARNING

2022-03-30 08:46 UTC, Orange-hanter commented on Client/Client.Core/Client.Core.Static/Client.cpp
> +    Base::Logger::FileLogger::getInstance().log("[Client][Warning] login answer is not implemented", Base::Logger::LogLevel::ERR);
The same as above

2022-03-30 08:46 UTC, Orange-hanter commented on Client/Client.Core/Client.Core.Static/Client.cpp
> +    Base::Logger::FileLogger::getInstance().log("[Client][Warning] server accepted is not implemented", Base::Logger::LogLevel::ERR);
same

2022-03-30 08:46 UTC, Orange-hanter commented on Client/Client.CLI/MainClient.cpp
> +                    Base::Logger::FileLogger::getInstance().log("some field is empty", Base::Logger::LogLevel::INFO);
Warning Log level

2022-03-30 08:46 UTC, Orange-hanter commented on Client/Client.CLI/App.cpp
> +        Base::Logger::FileLogger::getInstance().log("FAILED sending", Base::Logger::LogLevel::INFO);
Here should be ERROR

2022-03-30 08:46 UTC, Orange-hanter commented on Client/Client.CLI/App.cpp
> +        Base::Logger::FileLogger::getInstance().log("Unknown StoringMessageCode", Base::Logger::LogLevel::INFO);
And here WARNING

2022-04-06 12:35 UTC, Orange-hanter requested changes

2022-04-06 12:35 UTC, Orange-hanter commented on Client/Client.CLI/App.cpp
> +        Base::Logger::FileLogger::getInstance().log("Unknown RegistrationCode", Base::Logger::LogLevel::INFO);
warning level

2022-04-06 15:04 UTC, Orange-hanter reviewed
Client CLI need more atantion

2022-04-12 14:43 UTC, Orange-hanter approved these changes

2022-04-12 15:35 UTC, Orange-hanter commented
@memorisecodead @ivanboika please review this!

2022-04-12 18:32 UTC, ivanboika approved these changes

2022-04-12 19:05 UTC, merged