Interface class of popup message
f1nal3/Juniorgram pull request #508
Opened 2022-03-30 15:11 UTC by Agrifon

2022-03-30 15:15 UTC, f1nal3 commented on Client/Client.Qt/Widgets/I_PopupMessage/PopupMessage.cpp
> +    : I_PopupMessage(parent)
Pls check naming

2022-04-05 15:32 UTC, Orange-hanter requested changes

2022-04-05 15:32 UTC, Orange-hanter commented on Client/Client.Qt/CMakeLists.txt
> +        Widgets/PopupSystemMessage.hpp
Should be removed

2022-04-05 15:32 UTC, Orange-hanter commented on Client/Client.Qt/CMakeLists.txt
> +        Widgets/IPopupMessage/PopupMessage.hpp
Move to general folder

2022-04-05 15:32 UTC, Orange-hanter commented on Client/Client.Qt/Pages/RegistrationPage.hpp
> +#include <Widgets/IPopupMessage/IPopupMessage.hpp>
remove

2022-04-05 15:32 UTC, Orange-hanter commented on Client/Client.Qt/Widgets/IPopupMessage/PopupMessage.hpp
> +
Violation of styleguide

2022-04-05 15:32 UTC, Orange-hanter commented on Client/Client.Qt/Widgets/IPopupMessage/PopupMessage.hpp
> +    void  setPopupOpacity(float opacity) override;
styleguide is dead here!

2022-05-04 15:27 UTC, closed without merging