Transfer part of project Data access to use a Logger
f1nal3/Juniorgram pull request #511
Opened 2022-04-06 15:37 UTC by ivanboika

Task:
At the moment, the project has a utility for logging. Instead, we use output to standard error.
Do not do like this.

2022-04-07 12:51 UTC, memorisecodead approved these changes

2022-04-08 14:11 UTC, memorisecodead approved these changes

2022-04-12 15:30 UTC, Orange-hanter commented on DataAccess/DataAccess.Postgre/CMakeLists.txt
> +        PUBLIC CONAN_PKG::libpq CONAN_PKG::libpqxx
Rebase needed

2022-04-12 15:30 UTC, Orange-hanter commented on DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
> +            std::to_string(findIdChannel.value()[0][0].as<std::uint64_t>()) +
If the channel is not found, how to get it from the database?

2022-04-12 15:30 UTC, Orange-hanter commented on DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
> +            '[' + "channel id: " + std::to_string(findChannel.value()[0][1].as<std::uint64_t>()) +
If the channel is not found, how to get it from the database?

2022-04-12 15:30 UTC, Orange-hanter commented on DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
> +            std::to_string(findChannel.value()[0][1].as<std::uint64_t>()) +
The same...

2022-04-12 15:30 UTC, Orange-hanter commented on DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
> +            "] User id " + std::to_string(creatorlID) +
Looks confusing 
[channel id 213123] User id 666 is not the creator of channel id 1231321
better would be:
[channel id 213123] User id 666 is not the creator of this channel

2022-04-12 15:30 UTC, Orange-hanter commented on DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
> +        '[' + "channel id: " + std::to_string(channelID) +
Could be flooded, need testing

2022-04-12 15:30 UTC, Orange-hanter commented on DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
> +            " Editing message failed\n",
Not clear what happend

2022-04-12 15:30 UTC, Orange-hanter commented on DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
> +            "Invalid reaction info supplied",
Not clear what meaning

2022-04-12 15:32 UTC, Orange-hanter requested changes

2022-04-12 15:32 UTC, Orange-hanter commented on DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
> +            std::to_string(findIdChannel.value()[0][0].as<std::uint64_t>()) +
This should be changed

2022-04-12 19:21 UTC, ivanboika commented on DataAccess/DataAccess.Postgre/CMakeLists.txt
> +        PUBLIC CONAN_PKG::libpq CONAN_PKG::libpqxx
Already, or I'm mistaken

2022-04-13 10:45 UTC, ivanboika commented on DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
> +            std::to_string(findIdChannel.value()[0][0].as<std::uint64_t>()) +
Done

2022-04-13 10:47 UTC, ivanboika commented on DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
> +            '[' + "channel id: " + std::to_string(findChannel.value()[0][1].as<std::uint64_t>()) +
Fixed

2022-04-13 10:47 UTC, ivanboika commented on DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
> +            std::to_string(findChannel.value()[0][1].as<std::uint64_t>()) +
Fixed

2022-04-13 10:53 UTC, ivanboika commented on DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
> +            "] User id " + std::to_string(creatorlID) +
Done

2022-04-15 12:02 UTC, ivanboika commented on DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
> +            " Editing message failed\n",
Fixed

2022-04-15 12:13 UTC, ivanboika commented on DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
> +            "Invalid reaction info supplied",
Fixed

2022-04-18 15:49 UTC, Orange-hanter approved these changes

2022-04-18 15:49 UTC, Orange-hanter commented on DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
>          if (result.has_value())
There needs to be a reverse logic here, right?

2022-04-18 15:49 UTC, Orange-hanter commented on DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
>          if (result.has_value())
What should actually be returned  by the delete operation?

2022-04-18 15:49 UTC, Orange-hanter commented on DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
> +            Base::Logger::LogLevel::WARNING);
Error

2022-04-18 15:49 UTC, Orange-hanter commented on DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
> +            Base::Logger::LogLevel::WARNING);
done

2022-04-19 07:55 UTC, merged