Update GCC Linux Build.yml
f1nal3/Juniorgram pull request #515
Opened 2022-04-15 11:44 UTC by Orange-hanter

libx11-xcb-dev installed to system environment

2022-04-15 13:31 UTC, Orange-hanter commented
Fix description 
https://github.com/conan-io/conan-center-index/issues/6883

2022-04-17 11:07 UTC, ivanboika approved these changes

2022-04-18 11:03 UTC, f1nal3 requested changes

2022-04-18 11:03 UTC, f1nal3 commented on .github/workflows/GCC Linux Build.yml
> +      run: rm -rf ~/.conan/data/xorg
Use conan tools for removal

2022-04-18 12:33 UTC, f1nal3 approved these changes

2022-04-18 12:39 UTC, merged