Changed 'includes' to style guide
f1nal3/Juniorgram pull request #529
Opened 2022-04-25 14:55 UTC by ivanboika

Task: For the long time we didn't following the style, namely chapter Names rule 2. It's time to change that!
Acceptance Criteria:
Follow the rule and rename variables in proper way with underscore.

2022-04-28 16:29 UTC, memorisecodead approved these changes
Somethings good

2022-05-06 15:38 UTC, Orange-hanter requested changes

2022-05-06 15:38 UTC, Orange-hanter commented on DataAccess/DataAccess.SQLite/LiteAdapter.cpp
> +    *_DBConnection = QSqlDatabase::addDatabase("QSQLITE");
Camel case violation

2022-05-06 15:38 UTC, Orange-hanter commented on DataAccess/DataAccess.SQLite/LiteAdapter.cpp
> +    if (_SQLiteInstance == nullptr)
Camel case violation

2022-05-06 15:38 UTC, Orange-hanter commented on DataAccess/Public/Include/DataAccess/SQLStatements.hpp
> +
Space here not necessary

2022-05-06 19:51 UTC, ivanboika commented on DataAccess/DataAccess.SQLite/LiteAdapter.cpp
> +    *_DBConnection = QSqlDatabase::addDatabase("QSQLITE");
done

2022-05-06 19:51 UTC, ivanboika commented on DataAccess/DataAccess.SQLite/LiteAdapter.cpp
> +    if (_SQLiteInstance == nullptr)
done

2022-05-06 19:52 UTC, ivanboika commented on DataAccess/Public/Include/DataAccess/SQLStatements.hpp
> +
Erased one empty line

2022-05-10 17:14 UTC, Orange-hanter approved these changes

2022-05-10 19:34 UTC, merged