Server technical debt
f1nal3/Juniorgram pull request #554
Opened 2022-05-22 15:17 UTC by memorisecodead

## Server Style: 
1. Fixing shadowVariables.
2. Adding new checking functions in Server class for Message Handler.
3. Updating constructor of Server.
4. Adding new function for accepting connect of Client.
5. Edited comments according to the style guide.
6. New comments added.

2022-05-24 11:31 UTC, ivanboika commented on Server/Server.Core/Server.Core.Static/Server.hpp
> +    uint64_t _IDCounter         = 10000;
Both types of style guide are used, I had the same situation and solution was to lowercase the abbreviation because we all know what is id or, it was in my case, sql

2022-05-24 12:26 UTC, memorisecodead commented on Server/Server.Core/Server.Core.Static/Server.hpp
> +    uint64_t _IDCounter         = 10000;
> Both types of style guide are used, I had the same situation and solution was to lowercase the abbreviation because we all know what is id or, it was in my case, sql

I don't remember that we talked about this, as I know that we discussed that the variables in the class must be _underscore stylish. We'll ask @Orange-hanter today.

2022-05-24 14:47 UTC, Orange-hanter commented on Server/Server.Core/Server.Core.Static/Server.hpp
> +    uint64_t _IDCounter         = 10000;
We have a conversation on style guide, you may use next options: _idCounter, _counterId. (first one I like more)

2022-05-24 15:37 UTC, Orange-hanter requested changes

2022-05-24 15:37 UTC, Orange-hanter commented on Server/Server.Core/Server.Core.Static/ArgumentParser.cpp
> +    _arguments.try_emplace(key, stoi(value));
Reason of use try function?

2022-05-24 15:37 UTC, Orange-hanter commented on Server/Server.Exec/MainServer.cpp
> +        Base::Logger::FileLogger::getInstance().log
Namespace could be shorter in cpp file

2022-05-24 15:37 UTC, Orange-hanter commented on Server/Server.Core/Server.Core.Static/Server.cpp
>          {
Do we have reason to keep this brackets for now??

2022-05-24 15:37 UTC, Orange-hanter commented on Server/Server.Core/Server.Core.Static/Server.cpp
> +     _acceptor(_context, asio::ip::tcp::endpoint(asio::ip::tcp::v4(), port)),
Namespace could be shorter in cpp file

2022-05-24 15:37 UTC, Orange-hanter commented on Server/Server.Core/Server.Core.Static/Server.cpp
> +        ++messagesCount;
hello there ...

2022-05-24 16:19 UTC, memorisecodead commented on Server/Server.Core/Server.Core.Static/ArgumentParser.cpp
> +    _arguments.try_emplace(key, stoi(value));
If insert was called with a temporary, it leads to an extra copy or move construction and destruction of the temporary.  C++17 introduced try_emplace that does not construct the value if the key is already present in the map and constructs the value in place if necessary.  In most cases, you should use try_emplace.

2022-05-26 12:48 UTC, Orange-hanter commented on Server/Server.Core/Server.Core.Static/ArgumentParser.cpp
> +    _arguments.try_emplace(key, stoi(value));
Ok, fine

2022-05-26 12:49 UTC, Orange-hanter approved these changes

2022-05-26 15:01 UTC, ivanboika approved these changes

2022-05-26 15:28 UTC, merged