IRepository documentation
f1nal3/Juniorgram pull request #580
Opened 2022-06-30 18:35 UTC by slavexx

2022-07-07 12:19 UTC, slavexx commented
@Orange-hanter we have unresolved moment with 'IRepository' class. Check in issue #574

2022-07-18 11:54 UTC, slavexx commented
I pushed penultimate commit. Last commit aimed at removing intersections of lines. After that, i want to recheck the entire diagram, then PR will be opened

2022-07-19 11:49 UTC, slavexx commented
There is problem with displaying the "composition" relation (it displayed as simple line). Fix will be.

2022-07-30 14:28 UTC, memorisecodead commented on DataAccess/Public/Include/DataAccess/SQLStatements.hpp
> - *    SQLSelect, SQLUpdate and SQLUpdate. \
Lol, how is it passed review :3

2022-08-04 05:23 UTC, KliKonNik approved these changes

2022-08-04 09:45 UTC, ivanboika commented on DataAccess/Public/Include/DataAccess/AbstractRepositoryContainer.hpp
> + * @details Consists adapter to chosen database, and map of  registered repositories.
I'm sorry, but consists of

2022-08-04 09:46 UTC, ivanboika commented on DataAccess/Public/Include/DataAccess/IServerRepositories.hpp
> + * @brief Implements repies processing
typo

2022-08-04 09:48 UTC, ivanboika reviewed
Everything is almost done, just few typos

2022-08-04 09:59 UTC, slavexx commented on DataAccess/Public/Include/DataAccess/IServerRepositories.hpp
> + * @brief Implements repies processing
Fixed

2022-08-04 09:59 UTC, slavexx commented on DataAccess/Public/Include/DataAccess/AbstractRepositoryContainer.hpp
> + * @details Consists adapter to chosen database, and map of  registered repositories.
Fixed

2022-08-04 10:53 UTC, ivanboika approved these changes
Well done

2022-08-19 10:10 UTC, memorisecodead approved these changes

2022-09-05 12:24 UTC, Orange-hanter requested changes
In summary, documentation isn't great. Try to explain more details. Remember, you will forget half of that in weak. And another developer didn't curse you at night.

2022-09-05 12:24 UTC, Orange-hanter commented on DataAccess/Public/Include/DataAccess/IMasterRepository.hpp
> + * @details Class used as a base for client and server sides
Base for what?

2022-09-05 12:24 UTC, Orange-hanter commented on DataAccess/Public/Include/DataAccess/IServerRepositories.hpp
> +* @brief Implements message processing
What sort of processing do you mean?

2022-09-05 12:24 UTC, Orange-hanter commented on DataAccess/Public/Include/DataAccess/IMasterRepository.hpp
> + * @details Class used as a base for client and server sides
Also, where we should use that abstract class?

2022-09-05 12:24 UTC, Orange-hanter commented on DataAccess/Public/Include/DataAccess/IClientRepositories.hpp
> +    * @details Contains methods for client side for
All right, we locate on which side this interface should be used. But still we haven't any idea what for and how we should implement this class.

2022-09-05 12:24 UTC, Orange-hanter commented on DataAccess/Public/Include/DataAccess/IAdapter.hpp
> +    * @details Class manages the connection to database, stores options,
More details are needed. What mean "manages", it asks for some examples. Also, missed information about _query()_ method.
Where this adapter should be used are also unknown.

2022-09-05 12:24 UTC, Orange-hanter commented on DataAccess/Public/Include/DataAccess/AbstractRepositoryContainer.hpp
> + *  determined by further inheritance
1. Remove focus from client and server. What functionality does these class provide ?
2. Explain which class-repository could be registered

2022-09-05 12:24 UTC, Orange-hanter commented on DataAccess/Public/Include/DataAccess/QueryBuilder.hpp
> + * @brief Generates SQL query.
"Generate SQL query" is too wide an explanation. It is more of a helper class that provides an interface for building SQL queries.
A few examples can be given here.

2022-09-05 12:24 UTC, Orange-hanter commented on DataAccess/Public/Include/DataAccess/SQLStatements.hpp
> +* SQLSelect, SQLUpdate and SQLDelete. \
Clear dashes could have sense.

2022-09-07 13:24 UTC, slavexx commented on DataAccess/Public/Include/DataAccess/IAdapter.hpp
> +    * @details Class manages the connection to database, stores options,
We have information about *query()* in PostgreAdapter.hpp. Do i need to copy it here?

2022-09-13 09:51 UTC, Orange-hanter commented on DataAccess/Public/Include/DataAccess/IAdapter.hpp
> +    * @details Class manages the connection to database, stores options,
You could relate to other part of documentation.

2022-09-14 11:11 UTC, slavexx commented on DataAccess/Public/Include/DataAccess/IMasterRepository.hpp
> + * @details Class used as a base for client and server sides
Done

2022-09-14 11:12 UTC, slavexx commented on DataAccess/Public/Include/DataAccess/IServerRepositories.hpp
> +* @brief Implements message processing
Done

2022-09-14 11:12 UTC, slavexx commented on DataAccess/Public/Include/DataAccess/IClientRepositories.hpp
> +    * @details Contains methods for client side for
Done

2022-09-14 11:12 UTC, slavexx commented on DataAccess/Public/Include/DataAccess/IAdapter.hpp
> +    * @details Class manages the connection to database, stores options,
Done

2022-09-14 11:12 UTC, slavexx commented on DataAccess/Public/Include/DataAccess/AbstractRepositoryContainer.hpp
> + *  determined by further inheritance
Done

2022-09-14 11:12 UTC, slavexx commented on DataAccess/Public/Include/DataAccess/QueryBuilder.hpp
> + * @brief Generates SQL query.
Done

2022-09-14 11:12 UTC, slavexx commented on DataAccess/Public/Include/DataAccess/SQLStatements.hpp
> +* SQLSelect, SQLUpdate and SQLDelete. \
Done

2022-09-21 15:31 UTC, slavexx commented on DataAccess/Public/Include/DataAccess/IAdapter.hpp
> +    */
more info

2022-09-21 15:35 UTC, slavexx commented on DataAccess/Public/Include/DataAccess/IMasterRepository.hpp
> + * and server sides.
for what?

2022-09-21 15:40 UTC, slavexx commented on DataAccess/Public/Include/DataAccess/IServerRepositories.hpp
> +* @Class include methods for working with messages from database
Class -> detailed

2022-09-24 12:58 UTC, memorisecodead commented on DataAccess/Public/Include/DataAccess/IServerRepositories.hpp
> +* @Class include methods for working with messages from database
looks good

2022-09-28 14:05 UTC, slavexx commented
IMessageRepository (*IClientRepositoies.hpp*) isn`t used in the implementation for PostgreSQL, but used for SQLite DB, which is base on Qt

2022-09-28 15:06 UTC, slavexx commented on DataAccess/Public/Include/DataAccess/AbstractRepositoryManager.hpp
> +         *	@warning Pass all arguments (args) through 'fmt()' function
fix tabulation

2022-12-20 20:37 UTC, memorisecodead commented
I think we should raise the issue of rebuilding everything to a different pattern

2022-12-20 20:38 UTC, memorisecodead reviewed
I think we should raise the issue of rebuilding everything to a different pattern

2022-12-23 12:28 UTC, f1nal3 commented
Hey, @slavexx , since we're on the verge of a new release, please answer the following questions:
1) Do you still work on this PR?
2) How long will it take you to finish it?
3) Can it be reviewed and merged now?
4) How much will we lose if the just discard it?

2022-12-23 13:38 UTC, slavexx commented
@f1nal3,
    I`m waiting review from Daniil on written documentation. At the moment, work on PR is finished (unless changes are required in future). I`m not sure, that it`s a good idea to merge possible incorrect documentation. As far as I know, in future we will implement ORM and this will incur changes in structure of database access. In this case, by skipping this PR we will not lose anything.

2022-12-23 14:16 UTC, Orange-hanter approved these changes

2022-12-23 14:16 UTC, merged